apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-in-one
  labels:
    app: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-in-one
  template:
    metadata:
      labels:
        app: all-in-one
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: all-in-one
        image: awendt/all-in-one:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
